name: Test_Deploy
env:
  DEPLOY_ID: "deploy_id_is-${{ github.sha }}"

on: 
  push:
    branches: main 
    
jobs:
  my_testing:
    runs-on: ubuntu-latest
    
    steps:
     - name: Print Hello World     
       run : echo "Hello World, Print Step"
     - name: Print ID Deploy
       run : echo "Deploy id is ${{ env.DEPLOY_ID }}"
      
